# Logging configuration for Machine Learning module
# This file provides alternative logging configuration using YAML format

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s | %(name)s | %(levelname)s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s | %(name)s | %(levelname)s | %(filename)s:%(funcName)s:%(lineno)d | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "module": "%(filename)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  training_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/ml_training.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  prediction_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/ml_prediction.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  data_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/ml_data.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  cache_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/ml_cache.log
    maxBytes: 5242880   # 5MB
    backupCount: 3
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/ml_errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

loggers:
  ml_training:
    level: DEBUG
    handlers: [console, training_file, error_file]
    propagate: false
  
  ml_prediction:
    level: INFO
    handlers: [console, prediction_file, error_file]
    propagate: false
  
  ml_data:
    level: DEBUG
    handlers: [console, data_file, error_file]
    propagate: false
  
  ml_cache:
    level: INFO
    handlers: [console, cache_file, error_file]
    propagate: false
  
  feature_engineering:
    level: INFO
    handlers: [console, training_file, error_file]
    propagate: false
  
  mlflow_integration:
    level: INFO
    handlers: [console, training_file]
    propagate: false

root:
  level: INFO
  handlers: [console]