"""add check_date filed to weeklyqualitycheck

Revision ID: 00d1962da545
Revises: fef7bcd79b03
Create Date: 2025-06-21 23:02:21.588302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d1962da545'
down_revision: Union[str, None] = 'fef7bcd79b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitor', 'monitor_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('weekly_quality_check', sa.Column('check_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_quality_check', 'check_date')
    op.alter_column('monitor', 'monitor_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
