"""add distinct in weatherEvent

Revision ID: 11239de884d9
Revises: 342e076cc8b2
Create Date: 2025-07-14 23:38:42.431176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11239de884d9'
down_revision: Union[str, None] = '342e076cc8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_weather_event_unique', 'weather_event', ['rain_gauge_monitor_id', 'interim', 'event_type', 'area', 'start_time', 'end_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weather_event_unique', 'weather_event', type_='unique')
    # ### end Alembic commands ###
