"""add assigin_rain_gauge

Revision ID: 342e076cc8b2
Revises: aa1f96c754f0
Create Date: 2025-07-09 20:36:32.729550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342e076cc8b2'
down_revision: Union[str, None] = 'aa1f96c754f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor', sa.Column('assigned_rain_gauge_id', sa.Integer(), nullable=True))
    op.add_column('weather_event', sa.Column('rain_gauge_monitor_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_event', 'rain_gauge_monitor_id')
    op.drop_column('monitor', 'assigned_rain_gauge_id')
    # ### end Alembic commands ###
