"""add data_quality_check filed

Revision ID: 406658b6b775
Revises: 11239de884d9
Create Date: 2025-07-19 00:13:53.359521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406658b6b775'
down_revision: Union[str, None] = '11239de884d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_quality_check', sa.Column('data_quality_check', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_quality_check', 'data_quality_check')
    # ### end Alembic commands ###
