"""add interim_flied and velocity_flied

Revision ID: d081eb3ceee9
Revises: 00d1962da545
Create Date: 2025-06-27 19:22:32.719508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd081eb3ceee9'
down_revision: Union[str, None] = '00d1962da545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('interim', sa.Text(), nullable=True))
    op.add_column('measurement', sa.Column('velocity', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'velocity')
    op.drop_column('measurement', 'interim')
    # ### end Alembic commands ###
