"""change filed type

Revision ID: f7d3556cd397
Revises: 65b2ac3ad960
Create Date: 2025-07-06 19:24:39.173828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d3556cd397'
down_revision: Union[str, None] = '65b2ac3ad960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rain_gauge', 'intensity_mm_per_hr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('rain_gauge', 'interim',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('rain_gauge_timestamp_idx'), table_name='rain_gauge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('rain_gauge_timestamp_idx'), 'rain_gauge', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('rain_gauge', 'interim',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('rain_gauge', 'intensity_mm_per_hr',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
