""" adjust action and status_reason

Revision ID: f89c0f4417a2
Revises: d081eb3ceee9
Create Date: 2025-07-04 21:14:26.973855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89c0f4417a2'
down_revision: Union[str, None] = 'd081eb3ceee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_responsibility', 'action_type')
    op.add_column('monitor', sa.Column('status_reason', sa.Text(), nullable=True))
    op.add_column('weekly_quality_check', sa.Column('device_status', sa.String(), nullable=True))
    op.add_column('weekly_quality_check', sa.Column('device_status_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_quality_check', 'device_status_reason')
    op.drop_column('weekly_quality_check', 'device_status')
    op.drop_column('monitor', 'status_reason')
    op.add_column('action_responsibility', sa.Column('action_type', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
